name: CI

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use node 18.2.0
        uses: actions/setup-node@v2
        with:
          node-version: 18.2.0
      - name: Install dependencies
        run:
          npm ci --force
      - name: Run tests
        run: npm run test:unit